events {
    worker_connections 1024;
}

stream {
    upstream chat_backend {
        least_conn;
        server server-1:8881;
        server server-2:8882;
        server server-3:8883;
        server server-4:8884;
        server server-5:8885;
    }

    server {
        listen 8877;
        proxy_pass chat_backend;
        proxy_connect_timeout 30s;
        proxy_timeout 600s;
    }
}
